#!/bin/sh
# generate-skill-index.sh — regenerate markdowns/agents/skills-index.md from
# the .agents/skills/<name>/SKILL.md frontmatter.
#
# Walks every .agents/skills/<name>/SKILL.md, extracts the name + description,
# emits a sorted table. Runs from pre-commit so the index stays current with
# zero manual maintenance.
#
# Idempotent. Safe to run repeatedly. Soft-skips when .agents/skills/ doesn't
# exist (fresh clone, no skills authored yet).
#
# See: markdowns/meta-layer/cross-vendor-harness.md

set -e

REPO_ROOT=$(cd "$(dirname "$0")/.." && pwd)
AGENTS_SKILLS="$REPO_ROOT/.agents/skills"
INDEX="$REPO_ROOT/markdowns/agents/skills-index.md"

if [ ! -d "$AGENTS_SKILLS" ]; then
  exit 0
fi

# Stage the regenerated index when running under pre-commit so it ships
# in the same commit as the source skill edit (mirrors the sync-agents-md.sh
# pattern).
STAGE=0
if [ -d "$REPO_ROOT/.git" ] && { [ -n "${GIT_INDEX_FILE:-}" ] || [ -n "${PRE_COMMIT:-}" ] || [ "${1:-}" = "--stage" ]; }; then
  STAGE=1
fi

# Build the index in a temp file, then write atomically. Avoids leaving
# a half-written index if anything fails partway.
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

cat > "$TMP" <<'EOF'
---
name: skills-index
description: Auto-generated index of authored skills. Reads .agents/skills/<name>/SKILL.md frontmatter and emits a name + description table. Do not edit directly — regenerated by scripts/generate-skill-index.sh on every commit.
status: reference
---

<!-- skills-index.md — auto-generated by scripts/generate-skill-index.sh.
     Do not edit this file directly. Edit the skill SKILL.md frontmatter
     under .agents/skills/<name>/ instead; the pre-commit hook will
     regenerate this index on the next commit. -->

# Skills index

Auto-generated from `.agents/skills/<name>/SKILL.md` frontmatter. Walked by
the agent when deciding whether a skill already exists for a given trigger
shape.

| Skill | Description |
|---|---|
EOF

# Walk skills in sorted order so the index is stable across runs.
for SKILL_DIR in "$AGENTS_SKILLS"/*/; do
  [ -d "$SKILL_DIR" ] || continue
  SKILL_NAME=$(basename "$SKILL_DIR")
  SKILL_MD="$SKILL_DIR/SKILL.md"
  [ -f "$SKILL_MD" ] || continue

  # Extract description from frontmatter. Handles both single-line and
  # wrapped descriptions (folded YAML). Strips leading "description: "
  # and any trailing whitespace.
  DESCRIPTION=$(awk '
    /^---$/ { count++; if (count==2) exit; next }
    count==1 && /^description:/ {
      sub(/^description:[[:space:]]*/, "")
      print
    }
  ' "$SKILL_MD")

  # Default to "(no description)" if frontmatter is missing the field.
  # Pre-commit's check-skill-frontmatter.sh enforces description presence,
  # but a fresh clone without that hook could hit this branch.
  [ -z "$DESCRIPTION" ] && DESCRIPTION="(no description)"

  echo "| [\`$SKILL_NAME\`](../../.agents/skills/$SKILL_NAME/SKILL.md) | $DESCRIPTION |" >> "$TMP"
done | sort

# Move into place atomically.
mv "$TMP" "$INDEX"
trap - EXIT

if [ "$STAGE" = "1" ]; then
  git -C "$REPO_ROOT" add "$INDEX" 2>/dev/null || true
fi

echo "✅ Skill index regenerated at $INDEX"
