#!/bin/sh

# Regenerate every CLAUDE.md as a verbatim copy of its sibling AGENTS.md.
# AGENTS.md is the authored source (canonical instructions file, read
# natively by Codex CLI and Antigravity CLI). CLAUDE.md is mechanically
# duplicated so Claude Code (which reads CLAUDE.md natively) sees the same
# instructions the cross-vendor surface reads.
#
# Walks every AGENTS.md in the repo (excluding node_modules / .git / .next /
# .turbo / _archive / dist / build) and copies it to a sibling CLAUDE.md,
# prepending an auto-generated banner so editors don't waste time on files
# the next commit will overwrite.
#
# Idempotent. Safe to run repeatedly. Pre-commit hook enforces sync.
#
# See: markdowns/meta-layer/cross-vendor-harness.md

set -e

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)

cd "$REPO_ROOT"

# Banner prepended to every generated CLAUDE.md so anyone opening it sees
# the warning before they start editing.
BANNER='<!-- CLAUDE.md — auto-synced from AGENTS.md by scripts/sync-agents-md.sh.

     Do not edit this file directly. Edit AGENTS.md instead; the pre-commit
     hook will regenerate this file on the next commit and any edits here
     will be lost. -->

'

# Find every AGENTS.md outside vendored / generated / archived trees.
# Read paths with `while read -r` (not `for src in $LIST`) so filenames
# containing whitespace are walked correctly.
# Stage the regenerated mirror in the same commit as the source edit.
# Without this, pre-commit regenerates CLAUDE.md but doesn't add it to
# the index — the commit ships AGENTS.md changes with a stale CLAUDE.md,
# and the working tree carries the regenerated mirror forward as an
# untracked / unstaged change that leaks into the next commit.
# Only stage when running inside a git repo and inside a hook context;
# manual runs from a clean checkout shouldn't auto-stage.
STAGE_MIRRORS=0
if [ -d "$REPO_ROOT/.git" ] && [ -n "${GIT_INDEX_FILE:-}" -o -n "${PRE_COMMIT:-}" -o "${1:-}" = "--stage" ]; then
  STAGE_MIRRORS=1
fi

find . \
  -name 'AGENTS.md' \
  -not -path '*/node_modules/*' \
  -not -path '*/.git/*' \
  -not -path '*/.next/*' \
  -not -path '*/.turbo/*' \
  -not -path '*/.vercel/*' \
  -not -path '*/_archive/*' \
  -not -path '*/coverage/*' \
  -not -path '*/dist/*' \
  -not -path '*/build/*' \
  | sort \
  | while IFS= read -r src; do
      [ -z "$src" ] && continue
      dir=$(dirname "$src")
      dest="$dir/CLAUDE.md"
      printf '%s' "$BANNER" > "$dest"
      cat "$src" >> "$dest"
      [ "$STAGE_MIRRORS" -eq 1 ] && git add "$dest" 2>/dev/null || true
      echo "  $src → $dest"
    done

# Re-count via find rather than relying on the subshell counter
# (the while ran in a subshell under the pipe, so any in-loop counter
# would have been lost). This second find runs after every write has landed.
PAIR_COUNT=$(find . \
  -name 'CLAUDE.md' \
  -not -path '*/node_modules/*' \
  -not -path '*/.git/*' \
  -not -path '*/.next/*' \
  -not -path '*/.turbo/*' \
  -not -path '*/.vercel/*' \
  -not -path '*/_archive/*' \
  -not -path '*/coverage/*' \
  -not -path '*/dist/*' \
  -not -path '*/build/*' \
  | wc -l | tr -d ' ')

if [ "$PAIR_COUNT" -eq 0 ]; then
  echo "❌ No AGENTS.md files found under $REPO_ROOT. Nothing to sync." >&2
  exit 1
fi

echo "✅ Synced $PAIR_COUNT AGENTS.md → CLAUDE.md pair(s)."
